// Build-time QR generation. The page ships the matrix as data and never loads
// an encoder, so the hero has no runtime dependency and the code cannot be
// wrong at render time -- it was already correct when it was committed.
//
// The QR carries the vCard itself rather than a link, so scanning offers "add
// contact" natively: no page load, no second page to maintain, and it works
// with no signal at all. 170 characters lands at version 9 / 53x53 under ECC M,
// which is 1433 dark modules -- dense enough to build a detailed scene from,
// and still ~6.6px per module on a phone-sized hero.
import QR from "qrcode";
import { writeFileSync, mkdirSync } from "node:fs";

const NL = String.fromCharCode(10);
const PAYLOAD = [
  "BEGIN:VCARD",
  "VERSION:3.0",
  "N:Tai;Eric;;;",
  "FN:Eric Tai",
  "TITLE:Forward-deployed engineer",
  "EMAIL:eric@crewio.ai",
  "URL:https://cplog.github.io",
  "ADR;TYPE=WORK:;;;Hong Kong;;;",
  "END:VCARD",
].join(NL);

const q = QR.create(PAYLOAD, { errorCorrectionLevel: "M" });
const n = q.modules.size;
const bits = [...q.modules.data].map((v) => (v ? 1 : 0));

mkdirSync("../assets/card", { recursive: true });
writeFileSync(
  "../assets/card/qr.js",
  [
    "// GENERATED by cardbuild/gen.mjs -- do not edit.",
    `// vCard payload, version ${q.version}, ECC level M (15% damage tolerance).`,
    `export const SIZE = ${n};`,
    `export const BITS = "${bits.join("")}";`,
    "",
  ].join(NL)
);

// The same payload backs the download link, so the two can never disagree.
mkdirSync("../assets/card", { recursive: true });
writeFileSync("../assets/card/eric-tai.vcf", PAYLOAD + NL);

console.log(`qr.js — ${n}x${n}, ${bits.filter(Boolean).length} dark modules`);
