// Build-time QR generation. The page ships the matrix as data and never loads
// an encoder, so the card has no runtime dependency and the QR can never be
// wrong at render time -- it was already correct when it was committed.
import QR from "qrcode";
import { writeFileSync, mkdirSync } from "node:fs";

const URL_ = "https://cplog.github.io/card";
const q = QR.create(URL_, { errorCorrectionLevel: "H" });
const n = q.modules.size;
const bits = [...q.modules.data].map((v) => (v ? 1 : 0));

mkdirSync("../assets/card", { recursive: true });
writeFileSync(
  "../assets/card/qr.js",
  `// GENERATED by cardbuild/gen.mjs -- do not edit.\n` +
    `// ${URL_}  ·  version ${q.version}, ECC level H (30% damage tolerance)\n` +
    `export const SIZE = ${n};\n` +
    `export const URL = ${JSON.stringify(URL_)};\n` +
    `export const BITS = "${bits.join("")}";\n`
);
console.log(`qr.js written — ${n}x${n}, ${bits.filter(Boolean).length} dark modules`);
